# Generated by Django 3.2.16 on 2022-12-04 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(db_index=True, max_length=254, null=True, unique=True)),
                ('first_name', models.CharField(db_index=True, max_length=100)),
                ('middle_name', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('min_salary', models.FloatField()),
                ('max_salary', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='employee.user')),
                ('language', models.ManyToManyField(related_name='manager_language', to='employee.Language')),
            ],
            options={
                'abstract': False,
            },
            bases=('employee.user',),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='employee.user')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_job', to='employee.job')),
                ('language', models.ManyToManyField(related_name='employee_language', to='employee.Language')),
            ],
            options={
                'abstract': False,
            },
            bases=('employee.user', models.Model),
        ),
    ]
