apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    description: ''
  labels:
    appgroup: ''
    version: v1
  name: employee
  namespace: default
spec:
  selector:
    matchLabels:
      app: employee
      version: v1
  template:
    metadata:
      labels:
        app: employee
        version: v1
    spec:
      containers:
        - name: employee
          image: swr.ap-southeast-2.myhuaweicloud.com/practicum/employee:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: PAAS_APP_NAME
              value: employee
            - name: PAAS_NAMESPACE
              value: default
            - name: PAAS_PROJECT_ID
              value: b626c0f929fe4779b89d252305ca3444
            - name: POSTGRES_DB
              value: employee
            - name: POSTGRES_HOST
              value: postgres-employee
            - name: POSTGRES_USER
              value: root
            - name: POSTGRES_PORT
              value: '5440'
            - name: POSTGRES_PASSWORD
              value: '0074'
            - name: USERS_MS
              value: users
          resources:
            requests:
              cpu: 1000m
              memory: 1024Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
      imagePullSecrets:
        - name: default-secret
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      tolerations:
        - key: node.kubernetes.io/not-ready
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 300
        - key: node.kubernetes.io/unreachable
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 300
      volumes: []
      initContainers: []
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  progressDeadlineSeconds: 600

