image:
  repository: kong/kong-gateway
  tag: "3.0.1.0"

secretVolumes:
- kong-cluster-cert

admin:
  enabled: false

env:
  role: data_plane
  database: "off"
  cluster_mtls: pki
  cluster_control_plane: f4260a3d34.us.cp0.konghq.com:443
  cluster_server_name: f4260a3d34.us.cp0.konghq.com
  cluster_telemetry_endpoint: f4260a3d34.us.tp0.konghq.com:443
  cluster_telemetry_server_name: f4260a3d34.us.tp0.konghq.com
  cluster_cert: /etc/secrets/kong-cluster-cert/tls.crt
  cluster_cert_key: /etc/secrets/kong-cluster-cert/tls.key
  lua_ssl_trusted_certificate: system
  konnect_mode: "on"
  vitals: "off"

