apiVersion: v1
kind: Service
metadata:
  name: customer-svc
  namespace: app
  labels:
    app: customer
    version: v1
  annotations: {}
spec:
  selector:
    app: customer
    version: v1
  ports:
    - name: cce-service-0
      targetPort: 8002
      nodePort: 0
      port: 8002
      protocol: TCP
  type: ClusterIP
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack

