apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    description: ''
  labels:
    appgroup: ''
    version: v1
  name: gateway
  namespace: app
spec:
  selector:
    matchLabels:
      app: gateway
      version: v1
  template:
    metadata:
      annotations:
      labels:
        app: gateway
        version: v1
    spec:
      containers:
        - name: gateway
          image: swr.ap-southeast-3.myhuaweicloud.com/practicum/gateway:{{BUILDNUMBER}}
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: gateway-psql-cm
            - secretRef:
                name: db-secret
            - secretRef:
                name: customer-secret
          env:
            - name: PAAS_APP_NAME
              value: gateway
            - name: PAAS_NAMESPACE
              value: app
            - name: PAAS_PROJECT_ID
              value: 35772050ec54403784aecb2da548a31d
          resources:
            requests:
              cpu: 1000m
              memory: 1024Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
      imagePullSecrets:
        - name: default-secret
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      tolerations:
        - key: node.kubernetes.io/not-ready
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 300
        - key: node.kubernetes.io/unreachable
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 300
      volumes: []
      initContainers: []
  replicas: 2
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  progressDeadlineSeconds: 600

