# Generated by Django 3.2.16 on 2022-12-16 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('customer_first_name', models.CharField(max_length=200)),
                ('customer_last_name', models.CharField(max_length=200)),
                ('customer_phone_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('employee_first_name', models.CharField(max_length=200)),
                ('employee_last_name', models.CharField(max_length=200)),
                ('employee_phone_number', models.CharField(max_length=200)),
                ('employee_is_employee', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed', models.BooleanField(default=False)),
                ('property_type', models.CharField(blank=True, max_length=200, null=True)),
                ('sqft', models.PositiveIntegerField(blank=True, null=True)),
                ('room_number', models.PositiveIntegerField(blank=True, null=True)),
                ('year_built', models.PositiveIntegerField(blank=True, null=True)),
                ('floor', models.PositiveIntegerField(blank=True, null=True)),
                ('total_floor', models.PositiveIntegerField(blank=True, null=True)),
                ('bathroom_number', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('province', models.CharField(blank=True, max_length=50, null=True)),
                ('district', models.CharField(blank=True, max_length=50, null=True)),
                ('facade', models.CharField(blank=True, max_length=10, null=True)),
                ('close_to_school', models.BooleanField(default=False)),
                ('close_to_hospital', models.BooleanField(default=False)),
                ('close_to_railway', models.BooleanField(default=False)),
                ('close_to_station', models.BooleanField(default=False)),
                ('close_to_park', models.BooleanField(default=False)),
                ('has_security', models.BooleanField(default=False)),
                ('has_garage', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_demand', to='core.customer')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_demand', to='core.employee')),
            ],
        ),
    ]
