apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    description: ''
  labels:
    appgroup: ''
    version: v1
  name: employee
  namespace: default
spec:
  selector:
    matchLabels:
      app: employee
      version: v1
  template:
    metadata:
      labels:
        app: employee
        version: v1
    spec:
      containers:
        - name: employee
          image: swr.ap-southeast-2.myhuaweicloud.com/practicum/employee:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: PAAS_APP_NAME
              value: employee
            - name: PAAS_NAMESPACE
              value: default
            - name: PAAS_PROJECT_ID
              value: b626c0f929fe4779b89d252305ca3444
            - name: DEBUG
              value: '1'
            - name: DJANGO_SECRET_KEY
              value: laterlater
            - name: POSTGRES_DB
              value: employee
            - name: POSTGRES_HOST
              value: postgres-employee
            - name: POSTGRES_USER
              value: root
            - name: POSTGRES_PORT
              value: '5440'
            - name: POSTGRES_PASSWORD
              value: '0074'
            - name: USERS_MS
              value: users
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 250m
              memory: 512Mi
      imagePullSecrets:
        - name: default-secret
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      tolerations:
        - key: node.kubernetes.io/not-ready
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 300
        - key: node.kubernetes.io/unreachable
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 300
      volumes: []
      initContainers: []
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  progressDeadlineSeconds: 600


---
apiVersion: v1
kind: Service
metadata:
  name: employee
  namespace: default
  labels:
    app: employee
    version: v1
  annotations:
    kubernetes.io/elb.class: union
    kubernetes.io/elb.autocreate: >-
      {"type":"public","bandwidth_name":"cce-bandwidth-1671022838563","bandwidth_chargemode":"traffic","bandwidth_size":5,"bandwidth_sharetype":"PER","eip_type":"5_bgp"}
    kubernetes.io/elb.lb-algorithm: ROUND_ROBIN
    kubernetes.io/elb.health-check-flag: 'off'
spec:
  selector:
    app: employee
    version: v1
  externalTrafficPolicy: Cluster
  ports:
    - name: cce-service-0
      targetPort: 8001
      nodePort: 0
      port: 80
      protocol: TCP
  type: LoadBalancer

