
apiVersion: v1
kind: Service
metadata:
  name: postgres-users # Sets service name
  labels:
    app: postgres # Labels and Selectors
spec:
  selector:
    app: postgres
  ports:
    - port: 5433
      targetPort: 5432
      protocol: TCP


