# Generated by Django 3.2.16 on 2022-12-12 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('employee_first_name', models.CharField(max_length=200)),
                ('employee_last_name', models.CharField(max_length=200)),
                ('employee_phone_number', models.CharField(max_length=200)),
                ('employee_is_employee', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property_type', models.CharField(max_length=200)),
                ('sqft', models.PositiveIntegerField()),
                ('room_number', models.PositiveIntegerField()),
                ('year_built', models.PositiveIntegerField()),
                ('floor', models.PositiveIntegerField()),
                ('total_floor', models.PositiveIntegerField()),
                ('bathroom_number', models.PositiveIntegerField()),
                ('price', models.FloatField()),
                ('province', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('facade', models.CharField(max_length=10)),
                ('close_to_school', models.BooleanField(default=False)),
                ('close_to_hospital', models.BooleanField(default=False)),
                ('close_to_railway', models.BooleanField(default=False)),
                ('close_to_station', models.BooleanField(default=False)),
                ('close_to_park', models.BooleanField(default=False)),
                ('has_security', models.BooleanField(default=False)),
                ('has_garage', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_type', models.CharField(max_length=50)),
                ('advert_price', models.FloatField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_advert', to='core.employee')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_advert', to='core.product')),
            ],
        ),
    ]
