version: "3"
services:
  customer:
    depends_on:
      - user
      - employee
    build:
      context: ../../customer/app
      dockerfile: Dockerfile
    image: burakovali/customer
    env_file:
      - ../../customer/app/.env
    ports:
      - "8002:8002"

  user:
    build:
      context: ../../users/app
      dockerfile: Dockerfile
    image: burakovali/users
    env_file:
      - ../../users/app/.env
    ports:
      - "8000:8000"

  employee:
    depends_on:
      - user
    build:
      context: ../../employee/app
      dockerfile: Dockerfile
    image: burakovali/employee
    env_file:
      - ../../employee/app/.env
    ports:
      - "8001:8001"

  product:
    depends_on:
      - employee
      - user
      - customer
    build:
      context: ../../product/app
      dockerfile: Dockerfile
    image: burakovali/product
    env_file:
      - ../../product/app/.env
    ports:
      - "8003:8003"

