apiVersion: v1
kind: Service
metadata:
  name: mongo # Sets service name
  labels:
    app: mongo # Labels and Selectors
spec:
  ports:
    - port: 27017 # Sets port to run the postgres application
  selector:
    app: mongo

