
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo  # Sets Deployment name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo # Sets Image
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 27017
