apiVersion: v1
kind: Service
metadata:
  name: authentication-svc
  namespace: app
  labels:
    app: authentication
    version: v1
  annotations: {}
spec:
  selector:
    app: authentication
    version: v1
  ports:
    - name: cce-service-0
      targetPort: 8000
      nodePort: 0
      port: 8000
      protocol: TCP
  type: ClusterIP
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack

