# Generated by Django 3.2.16 on 2022-12-14 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.PositiveIntegerField()),
                ('customer_id', models.PositiveIntegerField()),
                ('employee_id', models.PositiveIntegerField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
