version: "3"
services:
  employee:
    depends_on:
      - postgres_employee
    build:
      context: ./app
      dockerfile: Dockerfile
    image: burakovali/employee
    env_file:
      - ./app/.env
    ports:
      - "8001:8001"
  postgres_employee:
    image: postgres
    restart: always
    command: -p 5440
    env_file:
      - ./app/.env
    expose:
      - 5440
    ports:
      - "5440:5440"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data:
