# Generated by Django 3.2.16 on 2022-12-14 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20221214_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sales',
            field=models.BooleanField(default=False),
        ),
    ]
