version: "3"
services:
  postgres_db:
    image: postgres
    restart: always
    env_file:
      - ./app/.env
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data:
