version: "3"
services:
  postgres_db:
    image: postgres
    restart: always
    env_file:
      - ./.env
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  postgres_db_2:
    image: postgres
    restart: always
    env_file:
      - ./.env2
    expose:
      - 5433
    ports:
      - "5433:5433"
    command: -p 5433
    volumes:
      - postgres_data_2:/var/lib/postgresql/data/
volumes:
  postgres_data:
  postgres_data_2: 
