version: "3"
services:
  postgres_product:
    image: postgres
    restart: always
    command: -p 5448
    env_file:
      - ./app/.env
    expose:
      - 5448
    ports:
      - "5448:5448"
    volumes:
      - postgres_product_dev:/var/lib/postgresql/data/
volumes:
  postgres_product_dev:
