version: "3"
services:
  postgres_notification:
    image: postgres
    restart: always
    command: -p 5435
    env_file:
      - ./app/.env
    expose:
      - 5435
    ports:
      - "5435:5435"
    volumes:
      - postgres_data_notification:/var/lib/postgresql/data/
volumes:
  postgres_data_notification:
