apiVersion: apps/v1
kind: Deployment
metadata:
  name: hr
  labels:
    app: hr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hr
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  template:
    metadata:
      labels:
        app: hr
    spec:
      containers:
        - name: hr
          image: docker.io/burakovali/hr:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: hr-configmap
            - secretRef:
                name: hr-secret